# basic settings
title = "Helfertool"
baseurl = "https://www.helfertool.org/"

theme = "helfertool"

[params]
titleblock_text = """Volunteer and staff management"""

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"

[[menu.main]]
name = "News"
weight = 10
identifier = "news"
url = "/news/"

[[menu.main]]
name = "GitHub"
pre = """<span class="githubicon" aria-hidden="true"></span>"""
weight = 100
identifier = "github"
url = "https://github.com/helfertool/helfertool"
