# basic settings
title = "Helfertool"
baseurl = "https://www.helfertool.org/"

theme = "helfertool"

disableRSS = true
disableSitemap = true

[params]
titleblock_text = """Volunteer and staff management"""

[[menu.main]]
name = "Home"
weight = 0
identifier = "home"
url = "/"
