# basic settings
title = "Helfertool"
baseurl = "http://example.org/"

theme = "helfertool"

disableRSS = true
disableSitemap = true

# multi lang
languageCode = "en-us"
DefaultContentLanguage = "en"

[params]
# template config
titleblock_text = """
    Helfermanagement"""

contact = """
    Sven Hertle<br />
    Wallnerstraße 39<br />
    80939 München<br />
    E-Mail: <a href="mailto:helfertool@fs.tum.de">helfertool@fs.tum.de</a>"""

[languages.en]
weight = 1
title = "Helfertool"

[languages.de]
weight = 2
title = "Helfertool"
