# basic settings
title = "Helfertool"
baseurl = "http://example.org/"

theme = "helfertool"

disableRSS = true
disableSitemap = true

[params]
titleblock_text = """
    Helfermanagement"""

[[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
